apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudml-sentinel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudml-sentinel
  template:
    metadata:
      labels:
        app: cloudml-sentinel
    spec:
      containers:
      - name: sentinel
        image: manaswini6/cloudml-sentinel:v3
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"