name: CloudML Sentinel CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: manaswini6i
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: manaswini6i/cloudml-sentinel:v4

      - name: Deploy Full Stack (App + Prometheus + Grafana)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 107.21.169.139
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cloudml-sentinel || (mkdir -p ~/cloudml-sentinel && cd ~/cloudml-sentinel)
            git pull origin main || true
            docker compose down || true
            docker compose up -d --build
            echo "✅ Full Stack Deployed Successfully!"
            echo "🌐 App        → http://$(curl -s ifconfig.me):8000"
            echo "📊 Prometheus → http://$(curl -s ifconfig.me):9090"
            echo "📈 Grafana    → http://$(curl -s ifconfig.me):3000"